### ISSUE TITLE
[Grant Application]: 

### ISSUE THREAD

**Issue by sofiqul60** [taikoxyz/grants#6]
### Project Description

1) Finx global As a moderator (https://discord.gg/jCGkhscN)

2) Polyhedra network as a ambassador (https://discord.gg/polyhedracommunity)

3)Sui global as regional moderator (https://discord.gg/suiglobalofficial)

4)Tapio finance as a moderator (https://discord.gg/dan5FNKBbd)

### Category

Zero-Knowledge Proofs (ZKP)

### Timeline

1) Finx global As a moderator (https://discord.gg/jCGkhscN)

2) Polyhedra network as a ambassador (https://discord.gg/polyhedracommunity)

3)Sui global as regional moderator (https://discord.gg/suiglobalofficial)

4)Tapio finance as a moderator (https://discord.gg/dan5FNKBbd)

### Project Plan

im a new comer

### Project Impact

lets build together

### Team Information

1) Finx global As a moderator (https://discord.gg/jCGkhscN)

2) Polyhedra network as a ambassador (https://discord.gg/polyhedracommunity)

3)Sui global as regional moderator (https://discord.gg/suiglobalofficial)

4)Tapio finance as a moderator (https://discord.gg/dan5FNKBbd)

### Point of Contact

email-isofiqul11@gmail.com

### Previous Work

I have been working on a moderation department pvt company since 5 years which is moderate Indian largest social media application, there I'm a quality analyst.
Check my LinkedIn profile here (https://www.linkedin.com/in/sofiqul-islam-2a1032179)

In the discord server I have many servers working as a moderator and ambassador 
I'll send you their link here so you can check manually

1) Finx global As a moderator (https://discord.gg/jCGkhscN)

2) Polyhedra network as a ambassador (https://discord.gg/polyhedracommunity)

3)Sui global as regional moderator (https://discord.gg/suiglobalofficial)

4)Tapio finance as a moderator (https://discord.gg/dan5FNKBbd)

### Additional Information

And additionally I'm multilangual like English, Bangladeshi and Indian (hindi, Bengali,Urdu, Assamese) language I'm proficient

### Agreement

- [X] I agree to comply with the terms and conditions of the grants program

**Comment by 2manslkh** [comment]
Does not fit the grants application criteria
